title: Balihoo Style Library
baseurl: "/style-library"
url: "http://balihoo.github.io/style-library"
description: >
  Balihoo's style library used on internal projects.

collections:
- elements
- forms

markdown: kramdown
highlighter: pygments
permalink: pretty

exclude: [node_modules, gulpfile.js, package.json, README.md, build]
